### ISSUE TITLE
Fix Coppermind links in events.json

### ISSUE THREAD

**Issue by jofwu** [Palanaeum/roshar-map#109]
The events.json file for the RoW/DS update (#100 ) has mixed up Coppermind links. The Coppermind link listed under each ID is listed in the ID AFTER the one it is supposed to be under.

Example: `"coppermind": "Oroden"` is under `"id": "ishikk"` when it should be under `"id": "oroden-is-born"` (the event preceding `ishikk` in events.json)

The Coppermind links are CORRECT up until `"coppermind": "Oroden"` From that point on, the Coppermind link for each event all need to "shift up by one event". (and I'll need to add one for the last)

I started to do this manually but @PaleoCrafter said he could fix this automatically.

**Comment by jofwu** [comment]
Making note of this here because I FORGOT about all of this and started to fix the links again before digging up our Discord conversation about it. XD

**Comment by PaleoCrafter** [comment]
@jofwu I've updated the events file on the branch, can you double check if everything is correct and close the issue if it's all fine again?

**Comment by jofwu** [comment]
Will do.

**Comment by jofwu** [comment]
Looks right on spot check. When I do my full review after everything is updated I'll double check.
