### ISSUE TITLE
Broken Events

### ISSUE THREAD

**Issue by jofwu** [Palanaeum/roshar-map#111]
The following events are included in events.json and have a marker on the timeline (for pr100). They also have a marker on the world map. But when you select them on the timeline, the screen doesn't center on the map marker and no card shows up.

I think it's just these 4 events:
* rysn-is-born
* renarin-discovers-the-gemstone-library
* creation-of-the-diagram
* navani-creates-antilight

**Comment by PaleoCrafter** [comment]
Fixed for events that I could fix in 0aaeac22a91bd1bc30b7cf1b6ef652e2f7146e39. There was a general bug with the behavior of changing URLs.  For the "Navani creates Antilight" event, however, the problem is that the image doesn't appear to exist yet.
