### ISSUE TITLE
Sort related events by date

### ISSUE THREAD

**Issue by jofwu** [Palanaeum/roshar-map#115]
The "Related Events" under character and location details should be sorted by event date if possible. 

Right now they're sorted alphabetically but the titles we give these are arbitrary, which makes finding a specific event in a long list difficult. It will be a lot more intuitive for someone (for example) looking at Urithiru details, if the related events are listed in chronological order.

**Comment by PaleoCrafter** [comment]
Implemented by befb21d73a378a6d19e095758fc4bbdbf858b58a
