### ISSUE TITLE
Event missing from timeline

### ISSUE THREAD

**Issue by jofwu** [Palanaeum/roshar-map#118]
The `adolin-is-born` is another one missing from the timeline. Click the event on the timeline and no card pops up. I checked that the image isn't missing and everything else about the event seems to be the same as the one just below (`kaladin-is-born`) so I'm out of ideas on what could be wrong...

**Comment by PaleoCrafter** [comment]
Fixed by 4170158e82ff5daed8dd852bd66e5ff2771b6569.
