### ISSUE TITLE
Winds-pleasure-attacked detail view not opening

### ISSUE THREAD

**Issue by jofwu** [Palanaeum/roshar-map#119]
The card for `winds-pleasure-attacked` opens just fine, but the detailed view isn't opening for me.

https://pr100.roshar-map.paleo.dev/#/en-US/events/winds-pleasure-attacked

![image](https://user-images.githubusercontent.com/8247331/134734109-1f7d9b51-474e-4fd9-9d3e-aef069254381.png)

**Comment by jofwu** [comment]
Happening with this one too:

https://pr100.roshar-map.paleo.dev/#/en-US/events/shallan-kills-tyn

**Comment by jofwu** [comment]
May have mentioned it previously but `venli-is-claimed-by-odium` is a case of one that won't even show a card. Has a marker on the timeline, but that's it.

**Comment by jofwu** [comment]
Okay, so I went through all of the events looking for various things, got all of my changes in, and now I'm looking at the latest instance of pr100...

Now the chard for `Adolin-is-born` won't come up and I'm *pretty sure* that was there before. Seems like you mentioned the error with all of this is happening when it builds the site, which I guess fits with that symptom? Anyways, just wanted to give that data point in case it's helpful.

**Comment by PaleoCrafter** [comment]
Fixed in 4170158e82ff5daed8dd852bd66e5ff2771b6569
