### ISSUE TITLE
[Editor]"Red" words of shadesmar map are not visible in editor mode

### ISSUE THREAD

**Issue by lianzhao** [Palanaeum/roshar-map#126]
Event view:
![image](https://user-images.githubusercontent.com/536786/140010547-a09b2742-f370-4435-a33c-df4c51dc0935.png)

Location view:
![image](https://user-images.githubusercontent.com/536786/140010586-fb1ae833-d114-4ead-b62d-a7a3dc041e7a.png)

**Comment by lianzhao** [comment]
https://github.com/Palanaeum/roshar-map/blob/96db23fb1f2566187834dbb01158dc174805d391/src/components/editor/Editor.vue#L579

Found out that if I change the color from black to any other color (e.g. white), it works fine
![image](https://user-images.githubusercontent.com/536786/140012437-ec676a94-9a62-4401-bdab-dd034e12617b.png)


BTW, the location of panatham oathgate seems to out of bounding box? See the screenshot above.

**Comment by PaleoCrafter** [comment]
Ah, thanks for pointing this out, @lianzhao! I changed something about the city dots and forgot to account for that in the editor. I'll fix it!

The Panatham Oathgate is fixed on the latest version of the `row-ds-update` branch :)
