### ISSUE TITLE
"The lesson" event

### ISSUE THREAD

**Issue by lianzhao** [Palanaeum/roshar-map#80]
[`translations/en/events/the-lesson.md`](https://github.com/Palanaeum/roshar-map/blob/master/translations/en/events/the-lesson.md)

> Shallan stole Jasnah's Soulcaster after Jasnah kills three thugs.

All four thugs were dead.

> they made their way out of the Palanaeum and into the city itself.

I think they were at Conclave at that time, not Palanaeum.

**Comment by jofwu** [comment]
Fixed.
